### PR TITLE
Proposed Version 4.0.0 

### LINKED ISSUE #22: Reading an archive content and then adding no files to it causes archive corruption
Thank you very much for developing ZipStorer. I have used it in several apps and until now I haven't encountered a problem.

In my last project I needed check a content of archive before add new files to avoid duplicate file names in that archive. I find out if I read an archive content and then I add no files into it to avoid duplicates causes an archive corruption.

See my test code. After first run a new archive is created. After second run an existing archive is opened and after check for duplicate file names in archive no files are added. And after that the whole archive is corrupted! And I opened only an existing archive, then I read its content, I wrote down no files and in the end I close it.

Do you have an idea where the problem might be?
```
const string archiveFilePath = @"C:\Temp\test.zip";
var archiveFileExists = File.Exists(archiveFilePath);
using (var zipArchive = archiveFileExists
  ? ZipStorer.Open(archiveFilePath, FileAccess.ReadWrite)
  : ZipStorer.Create(archiveFilePath, "TestArchive"))
{
  var zipFileEntries = archiveFileExists
    ? zipArchive.ReadCentralDir()
    : new List<ZipStorer.ZipFileEntry>();
  for (int i = 0; i < 10; i++)
  {
    if (zipFileEntries.Any(e => e.FilenameInZip == $"TestFile_{i + 1:00}.txt")) continue;
    using (var memoryStream = new MemoryStream())
    using (var streamWriter = new StreamWriter(memoryStream))
    {
      streamWriter.WriteLine("TEST!");
      streamWriter.Flush();
      memoryStream.Seek(0, SeekOrigin.Begin);
      zipArchive.AddStream(ZipStorer.Compression.Deflate, $"TestFile_{i + 1:00}.txt", memoryStream, 
      DateTime.Now, string.Empty);
    }
  }
}
```

### LINKED ISSUE #39: Not Working Support for Zip64 (file sizes > 4GB)
Your helper file is very much useful, I have used in my 3-5 projects but when I used in recent project where zipping was of more than 6gb folder, zip file was generating successfully but unzipping was making issue in checksum error.

After going through your code and comments I found that support for larger sizes file you have changed the WriteEndRecord parameter size but not changed in close function to send the value for the same so I have changed some little two things in two lines of your code.

Please change the data type in ### close() function at line###  334, 335 from **uint** to **long** as when there is bigger sizes files the stream position is at greater than the uint max size.

Please look the same and do changes for making this more awesome successful code. 

        /// <summary>
        /// Updates central directory (if pertinent) and close the Zip storage
        /// </summary>
        /// <remarks>This is a required step, unless automatic dispose is used</remarks>
        public void Close()
        {
            if (this.Access != FileAccess.Read)
             {
                long centralOffset = this.ZipFileStream.Position;
                long centralSize = 0;

                if (this.CentralDirImage != null)
                    this.ZipFileStream.Write(CentralDirImage, 0, CentralDirImage.Length);

                for (int i = 0; i < Files.Count; i++)
                {
                    long pos = this.ZipFileStream.Position;
                    this.WriteCentralDirRecord(Files[i]);
                    centralSize += (uint)(this.ZipFileStream.Position - pos);
                }

                if (this.CentralDirImage != null)
                    this.WriteEndRecord(centralSize + (uint)CentralDirImage.Length, centralOffset);
                else
                    this.WriteEndRecord(centralSize, centralOffset);
            }

            if (this.ZipFileStream != null && !this.leaveOpen)
            {
                this.ZipFileStream.Flush();
                this.ZipFileStream.Dispose();
                this.ZipFileStream = null;
            }
        }

After changing code then to file extraction giving error of checksum please look in this issue.

### LINKED ISSUE #43: Error encoding 437 .net core 3.1
Raise this error
No data is available for encoding 437. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

as workaround i comment the lines
private static Encoding DefaultEncoding = Encoding.UTF8/* Encoding.GetEncoding(437)*/;

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
This goes much farther than my first PR, into the realm of breaking changes. 

 - One class per file
 - Make public fields properties
 - Do not use Microsoft namespaces!
 - C# naming conventions
 - Implement async
 - Add ExtractToFolder
 - Always put Dispose in Finally or using
 - Refactor and cleanup
 - Closes #39
 - Closes #22
 - Closes https://github.com/jaime-olivares/zipstorer/issues/37
 - Closes #43 
 - Closes https://github.com/jaime-olivares/zipstorer/issues/48

### CODE REVIEW

**Comment by A9G-Data-Droid** [comment]
Now closes #48

**Comment by A9G-Data-Droid** [comment]
It might be easier to review and merge #50 first, as this one is build upon that same branch.

**Comment by andreoromera** [comment]
Any updates?
Client is constantly complaining about this.
They need to upload files bigger than 4gb.
Any help would be truly appreciated!

**Comment by A9G-Data-Droid** [comment]
Have you tested my branch? You can review the code yourself and use my version until this is accepted.

**Comment by jaime-olivares** [comment]
I am sorry. I cannot accept this PR, for the following reasons:
- It covers too many aspects at a time.
- It changes the structure of the source code files (it was a one-filer)
- It changes the namespace, breaking all code from existing users
- It removes the build of other platforms than .net standard 2.0, that many users may be using
- Hard to track changes as too many files are renamed/relocated

**Pull request closed without merging**
