### PR TITLE
Fixed errors in VB version

### PR DESCRIPTION
**Pull request by cloudflying**
Corrected problems with line endings / comment wraps.

### CODE REVIEW

**Comment by jaime-olivares** [comment]
Hi there, I have tried to understand what you have corrected, but as you have changed all the spacing in the source code file, every single line looks like a change.

**Comment by cloudflying** [comment]
Hi, 
That was actually what I fixed. The spacing / line breaks were out of whack and wouldn't build / compile correctly. Then I am sure some Visual Studio voodoo happened when saving as well. 

Here is diffcheckers version of the two files side by side, still not great, but a little easier to see what changes I made.

https://www.diffchecker.com/loowokws

If you want I can close this pull request and mark up exactly which lines I updated.

Justin.

**Comment by jaime-olivares** [comment]
Hi Justin, could you please start over without moving the tab spacing? I think that will better reflect your changes.

**Comment by cloudflying** [comment]
Yes, that was on my list of things to do today. Plus I am going to use Sublime instead of Visual Studio.

Justin
________________________________

**Comment by cloudflying** [comment]
I have updated the file and it should give you a better overview of the changes.

Justin

**Comment by jaime-olivares** [comment]
Got it. Thanks for your contribution.

**Pull request merged**
